WIP Add user profile
allegro/ralph_pricing pull request #505
Opened 2016-09-08 13:22 UTC by szok

2016-09-08 13:46 UTC, mkurek commented on setup.py
> +            'ralph-scrooge = ralph_scrooge.__main__:main',
Just scrooge

2016-09-08 13:48 UTC, mkurek commented on src/ralph_scrooge/models/owner.py
> +    home_page = ChoiceField(
This Field is not necessary

2016-09-08 13:49 UTC, mkurek commented on src/ralph_scrooge/models/owner.py
> +    avatar_field = partial(
Rm all avatar fields too

2016-09-08 13:51 UTC, mkurek commented on src/ralph_scrooge/urls.py
>  from __future__ import print_function
We have to keep `/scrooge/...` url too for backward compatibility

2016-09-08 13:55 UTC, mkurek commented on src/ralph_scrooge/urls.py
>  from __future__ import print_function
But only for (external) api - remember about v0.9 😉

2016-09-12 05:22 UTC, mkurek commented on src/ralph_scrooge/models/owner.py
> +    time_zone = db.FloatField(_('Time zone'), choices=TZ_CHOICES, default=1.0)
we don't need this

2016-09-12 05:22 UTC, mkurek commented on src/ralph_scrooge/models/owner.py
> +class AvailableHomePage(Choices):
remove it

2016-09-12 15:06 UTC, mkurek commented on src/ralph_scrooge/settings.py
> +    'lck.django.common.middleware.ForceLanguageCodeMiddleware',
lck? :)

2016-09-12 15:06 UTC, mkurek commented on src/ralph_scrooge/settings.py
> +    'bob',
no more bob! :)

2016-09-12 15:06 UTC, mkurek commented on src/ralph_scrooge/settings.py
> +    'ajax_select',
we don't need this

2016-09-12 15:07 UTC, mkurek commented on src/ralph_scrooge/settings.py
> +RQ_QUEUE_LIST = ('reports_pricing',)
add also `scrooge_costs_master`, `scrooge_costs`, `scrooge_report`

2016-09-12 15:08 UTC, mkurek commented on src/ralph_scrooge/tests/plugins/collect/test_openstack_base.py
> +        self.assertEqual(result, 1404231133.0)
why? :)

2016-09-12 15:08 UTC, mkurek commented on src/ralph_scrooge/tests/test_api.py
> -# -*- coding: utf-8 -*-
this file should stay as it is

2016-09-12 15:09 UTC, mkurek commented on src/ralph_scrooge/tests/test_security.py
> +    def test_components_accountant_permission_denied(self):
test here if superuser has access

2016-09-12 15:10 UTC, mkurek commented on src/ralph_scrooge/urls.py
> +    url(r'^scrooge/api/', include(v09_router.urls)),
could we include it under '/api/' too? And it'd be great to include this whole "rest" thing under this endpoint too

2016-09-13 12:58 UTC, szok commented on src/ralph_scrooge/tests/test_security.py
> +    def test_components_accountant_permission_denied(self):
is in: https://github.com/szok/ralph_pricing/blob/149e59a570670aa5247ed4b0673ffa1cab459109/src/ralph_scrooge/tests/test_security.py#L81

2016-09-13 12:58 UTC, szok commented on src/ralph_scrooge/urls.py
> +    url(r'^scrooge/api/', include(v09_router.urls)),
done.

2016-09-14 10:25 UTC, mkurek commented on src/ralph_scrooge/migrations/0027_auto__add_userprofile__chg_field_historicalservice_modified_by__chg_fi.py
> +        db.alter_column('ralph_scrooge_historicalservice', 'modified_by_id', self.gf('django.db.models.fields.related.ForeignKey')(on_delete=models.SET_NULL, to=orm['auth.User'], null=True))
do we have `auth.User` app and model right now?

2016-09-14 10:26 UTC, mkurek commented on src/ralph_scrooge/models/owner.py
> +class UserProfile(db.Model):
what about ldap sync? :)

2016-09-14 10:28 UTC, mkurek commented on src/ralph_scrooge/settings.py
> +DEBUG = True
what about including custom settings (from `~/.ralph/settings`)?

2016-09-14 10:31 UTC, szok commented on src/ralph_scrooge/settings.py
> +DEBUG = True
Using DJANGO_SETTINGS_MODULE :)

2016-09-15 07:56 UTC, szok commented on src/ralph_scrooge/models/owner.py
> +class UserProfile(db.Model):
Done

2016-09-19 09:00 UTC, xor-xor commented on src/ralph_scrooge/utils/demo.py
> +                return
What about providing some info (warning/info) here..?

2016-09-19 09:03 UTC, xor-xor commented on src/ralph_scrooge/utils/security.py
> +    Check if user is superuser.
The relation between this description and function's name is not so obvious, IMO (hint: I'd change function's name) ;)

2016-09-19 09:07 UTC, xor-xor commented on Makefile
> +	dev_scrooge runserver
Out of curiosity - why `dev_scrooge` instead of just `scrooge`..?

2016-09-19 09:07 UTC, xor-xor commented on src/ralph_scrooge/__main__.py
> +    # default DJANGO_SETTINGS_MODULE is overwrited in .profile
s/usefull/useful/
s/vagrant/Vagrant/
s/overwrited/overwritten/

2016-09-19 09:07 UTC, xor-xor commented on src/ralph_scrooge/migrations/0021_warehouses_to_datacenters.py
> +    pass
What about adding here some `logger.warning` or `logger.info`..?

2016-09-19 09:07 UTC, xor-xor commented on src/ralph_scrooge/models/owner.py
> +class UserProfile(db.Model):
@szok - where..? ;)

2016-09-19 09:07 UTC, xor-xor commented on src/ralph_scrooge/models/owner.py
> +        # no such table yet, first syncdb
What do you mean by "first syncdb"..? Is it something that has to be done by user..? If yes, what about giving him/her some message about that (i.e., logger.info/logger.warning)..?

2016-09-19 09:07 UTC, xor-xor commented on src/ralph_scrooge/utils/demo.py
> +        raise NameError('This key ({}) already exist.'.format(demo_klass.name))
s/exist/exists/

2016-09-19 09:07 UTC, xor-xor commented on src/ralph_scrooge/utils/demo.py
> +        raise NotImplementedError('Please specify name')
"name" of what..?

2016-09-19 09:07 UTC, xor-xor commented on src/ralph_scrooge/utils/demo.py
> +        raise NotImplementedError('Please specify title')
"title" of what..?

2016-09-19 09:07 UTC, xor-xor commented on src/ralph_scrooge/utils/demo.py
> +        """This method find reqiurement of demo data and call execute method
s/find/finds/

2016-09-19 09:07 UTC, xor-xor commented on src/ralph_scrooge/utils/demo.py
> +        raise NotImplementedError('Please override')
What about `'Please override "generate_data" method'` or something like that..?

2016-09-19 09:07 UTC, xor-xor commented on src/ralph_scrooge/utils/demo.py
> +            """Method search all requirements for demo and add or update
I'd expand this description a bit. For example, how these requirements are specified / passed here..? And maybe some other name for this function (this is not a method, btw), because `dig_requirements` is kind of ambiguous IMO.

2016-09-19 12:49 UTC, szok commented
Add logging settings from Ralph 2

2016-09-20 07:05 UTC, szok commented on Makefile
> +	dev_scrooge runserver
scrooge is for the production (settings.prod)
dev_scrooge is for the development (settings.dev)

2016-09-22 08:55 UTC, xor-xor commented on Makefile
> +	dev_scrooge runserver
So why not `scrooge_dev` then..? ;) We already have `test_scrooge` command here, so I'd go with the suffix version, because now it kind of suggests that these two commands are somehow related (while they are not - the former runs tests on Scrooge, and the latter runs Scrooge itself).

2016-09-26 12:02 UTC, mkurek commented on src/ralph_scrooge/settings/base.py
> +    'tastypie',
no need for this after merging #507

2016-09-26 12:05 UTC, mkurek commented on src/ralph_scrooge/settings/base.py
> +    'reports_pricing', 'scrooge_costs_master', 'scrooge_costs', 'scrooge_repor'
scrooge_report

2016-09-26 12:06 UTC, mkurek commented on src/ralph_scrooge/settings/base.py
> +        'mail_admins': {
no need for this handler

2016-09-26 12:06 UTC, mkurek commented on src/ralph_scrooge/settings/base.py
> +        'require_debug_false': {
i'd not use this filter. rm it

2016-09-26 12:10 UTC, mkurek commented on src/ralph_scrooge/settings/base.py
> +        'plugins': {
what plugins?

2016-09-26 12:10 UTC, mkurek commented on src/ralph_scrooge/settings/base.py
> +        'ralph_scrooge.management.commands.scrooge_sync': {
ralph_scrooge.management.commands.scrooge_sync -> ralph_scrooge

2016-09-26 12:10 UTC, mkurek commented on src/ralph_scrooge/settings/base.py
> +        'critical_only': {
rm it

2016-09-26 12:11 UTC, mkurek commented on src/ralph_scrooge/settings/test.py
> +PLUGGABLE_APPS = ['scrooge']
there is no pluggable apps anymore

2016-09-26 12:14 UTC, mkurek commented on src/ralph_scrooge/urls.py
> +    url(r'^api/', include(v09_api.urls, namespace='api')),
mv it to `rest/` right now - we'll organize it and then gradually move it to `api/` resource.

2016-09-26 12:14 UTC, mkurek requested changes

2016-09-26 12:14 UTC, mkurek commented on Makefile
> +	dev_scrooge runserver
we're using `[dev|test]_scrooge` convention to use it only by users aware of it, not by users who type `scroo` in terminal and will be confused seeing multiple options (scrooge, scrooge_test, scrooge_dev)

2016-09-26 12:14 UTC, mkurek commented on src/ralph_scrooge/management/commands/ldap_sync.py
> +# https://raw.githubusercontent.com/allegro/ralph/develop/src/ralph/account/management/commands/ldap_sync.py  # noqa
ralph2 + ralph3 + dnsaas (https://github.com/allegro/django-powerdns-dnssec/pull/149/files) - it's really time for making small (django) package of it

2016-09-26 12:14 UTC, mkurek commented on src/ralph_scrooge/migrations/0021_warehouses_to_datacenters.py
> -    models = {
id keep models and other south metainformation untact

2016-09-27 09:53 UTC, xor-xor commented on setup.py
> +        'South==0.7.6',
Since #507, the required version of South is `1.0.2` (DjRF's authtoken app won't work with South < 1.x).

2016-09-27 09:55 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_migrate_api_keys.py
> +    print('Tastypie is not installed. Please instal it.')
s/instal/install/ ;)

2016-09-27 09:55 UTC, szok commented on setup.py
> +        'South==0.7.6',
Done :)

2016-09-27 10:00 UTC, xor-xor commented
:ok:

2016-09-27 10:03 UTC, szok commented on src/ralph_scrooge/management/commands/scrooge_migrate_api_keys.py
> +    print('Tastypie is not installed. Please instal it.')
Done

2016-09-28 06:42 UTC, mkurek approved these changes

2016-09-28 06:42 UTC, mkurek commented on setup.py
> +        'rq-scheduler==0.3.6',
where do we use scheduler?

2016-09-28 09:30 UTC, merged