Migrate API to DjRF
allegro/ralph_pricing pull request #507
Opened 2016-09-12 14:29 UTC by xor-xor

Preview only! Do not merge yet!

2016-09-13 09:05 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +        model = PricingServiceUsageObject
do we need model here? imo it's not `ModelSerializer`, so there is no need for specifying model here (and we don't need this `PricingServiceUsageObject` etc model either - we could operate on python structures, like dict)

2016-09-13 09:06 UTC, mkurek commented on src/ralph_scrooge/rest/urls.py
> +        r'^pricingserviceusages/(?P<pricing_service_id>[\w\d\s_.-]+)/(?P<date>[\d-]+)/$',
pricing service id could only be number

2016-09-13 09:07 UTC, mkurek commented on src/ralph_scrooge/rest/urls.py
> +        r'^pricingserviceusages/(?P<pricing_service_id>[\w\d\s_.-]+)/(?P<date>[\d-]+)/$',
could you make some extended regex for date (to match YYYY-MM-DD)?

2016-09-13 09:08 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +    def get(self, request, *args, **kwargs):
couldn't `date` and `pricing_service_id` be specified here, as method params?

2016-09-13 09:12 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +        deserializer = PricingServiceUsageObjectDeserializer(data=post_data)
isn't `deserializer = PricingServiceUsageObjectDeserializer(data=request.data)` working?

2016-09-13 09:13 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +            self.save_usages(post_data)
why not passing serializer here?

2016-09-13 09:17 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +        usage_types = {}  # XXX there's such empty dict in old API's code
this could be moved to (cached) method to get usage type by symbol

2016-09-13 09:19 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +            pricing_object = PricingObject.objects.get(
i don't know if there is need for try-except - it should be handled at validation level - imo validation could already fetch right objects (UsageType, PricingObject, ServiceEnvironment etc) to this dict

2016-09-13 11:20 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +    def get(self, request, *args, **kwargs):
Done.

2016-09-13 11:23 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +        deserializer = PricingServiceUsageObjectDeserializer(data=post_data)
Done.

2016-09-13 11:45 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +            self.save_usages(post_data)
You mean:
`self.save_usages(deserializer)`
or:
`self.save_usages(deserializer.object)`
?

2016-09-13 14:02 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +        usage_types = {}  # XXX there's such empty dict in old API's code
As discussed face-to-face - we won't be touching this now.

2016-09-13 14:04 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +        model = PricingServiceUsageObject
I'll try dict-based approach here as well, and see which one will be better.

2016-09-13 14:16 UTC, xor-xor commented on src/ralph_scrooge/rest/urls.py
> +        r'^pricingserviceusages/(?P<pricing_service_id>[\w\d\s_.-]+)/(?P<date>[\d-]+)/$',
Done.

2016-09-26 07:16 UTC, mkurek commented on doc/api.rst
> +              ("service": "<service name>" | "service_id": <service ID> | "service_uid": "<service UID>"),
service ID -> service ID (in Scrooge)

2016-09-26 07:19 UTC, mkurek commented on doc/api.rst
> +generated in Scrooge's Admin.
provide some example in this section too (i know it's later in example, but imo `Authorization: ApiKey <user name>:<API key from Scrooge Admin>` should be placed here, and later in example we should operate on "real" data, like `Authorization: ApiKey my_technical_user: 8356dd1592c789e946039774e00f72019c93c5ea `

2016-09-26 07:20 UTC, mkurek commented on doc/api.rst
> +* ``delete_all_previous`` - all previously upladed daily usages for
uploaded

2016-09-26 07:20 UTC, mkurek commented on doc/api.rst
> +  date, with the same usage type *and the same service environment*
service env or pricing object

2016-09-26 07:21 UTC, mkurek commented on doc/api.rst
> +400 - invalid symbol or name (e.g. usage type or service) - such error
maybe invalid data in general?

2016-09-26 07:31 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +# TODO(xor-xor): Consider json-schema based approach instead of all of those
👍

2016-09-26 07:34 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +class TastyPieLikeTokenAuthentication(TokenAuthentication):
could you move it to other (dedicated) module?

2016-09-26 07:35 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +            "Service with ID {} does not exist.".format(pricing_service_id)
Service -> Pricing Service

2016-09-26 07:36 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +    usages = get_usages(usages_date, pricing_service_id)
you could store result of `PricingService.objects.get(id=pricing_service_id)` in some variable and pass it to `get_usages`

2016-09-26 07:39 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +        if se.dummy_pricing_object != dpo.pricing_object:
we could check dpo.pricing_object.type here (and compare it with PRICING_OBJECT_TYPES.DUMMY) - it should be faster (no need to fetch dummy pricing object for service env)

2016-09-26 07:40 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +def get_usages_for_save(pricing_service_usage):
could you add some docstrings for not-obvious methods here (longer than few lines)?

2016-09-26 07:42 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +                UsageType.objects.get(symbol=usage['symbol'])
it'll not work as a cache - python will evaluate `UsageType.objects.get(symbol=usage['symbol'])` before fetching item from dict - use maybe try-except instead

2016-09-26 07:45 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +def save_usages(pricing_service_usage):
wrap it in db transaction (decorator)

2016-09-26 07:46 UTC, mkurek requested changes

2016-09-26 07:46 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +    service_id = serializers.IntegerField()
you could add `service_uid` field here too

2016-09-26 07:46 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +class UsagesSerializer(Serializer):
couldn't we (re)use `UsagesDeserializer` for both serialization and deserialization? since we're serializing objects, we don't need `required` params or it could be set to False - it's only relevant to the user data

2016-09-26 07:46 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +        except ServiceEnvironment.DoesNotExist:
there could be the case when multiple `ServiceEnvironment`s will be returned as well (ex. when user provides name of the service)

2016-09-26 08:26 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +class UsagesSerializer(Serializer):
I'd leave them as separate entities, for clarity - I think that the lack of symmetry here, while having it other cases (i.e. `UsageSerializer` / `UsageDeserializer`, `PricingServiceUsageSerializer` / `PricingServiceUsageDeserializer`) may be confusing. In other words, I prefer consistency even if it costs extra few lines of code :wink:

2016-09-26 08:30 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +# TODO(xor-xor): Consider json-schema based approach instead of all of those
OK, so I'll leave this TODO here and come back for it when we finally separate Scrooge from Ralph (I'll create a ticket for it in our JIRA as well).

2016-09-26 08:42 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +class UsagesSerializer(Serializer):
ok

2016-09-26 08:46 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +    service_id = serializers.IntegerField()
Done (although keep in mind, that this field wasn't a part of the original API, so it may cause problems on receivers' part).

2016-09-26 09:00 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +        except ServiceEnvironment.DoesNotExist:
Done (such case will result in validation error).

2016-09-26 09:03 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +class TastyPieLikeTokenAuthentication(TokenAuthentication):
I'm not sure if such move makes sense now - i.e. it's just one, small class which is only used here. I'd consider a separate module for this when we would have some other, cutom auth scheme or if this scheme would be used in some other places as well.

2016-09-26 09:04 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +            "Service with ID {} does not exist.".format(pricing_service_id)
Done.

2016-09-26 09:10 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +    usages = get_usages(usages_date, pricing_service_id)
Done.

2016-09-26 09:12 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +def save_usages(pricing_service_usage):
You mean `django.db.transaction.commit_on_success` or something else..?

2016-09-26 10:14 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +        if se.dummy_pricing_object != dpo.pricing_object:
Done.

2016-09-26 10:28 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +                UsageType.objects.get(symbol=usage['symbol'])
Done.

2016-09-26 10:30 UTC, xor-xor commented on doc/api.rst
> +400 - invalid symbol or name (e.g. usage type or service) - such error
Done.

2016-09-26 10:32 UTC, xor-xor commented on doc/api.rst
> +  date, with the same usage type *and the same service environment*
Done.

2016-09-26 10:32 UTC, xor-xor commented on doc/api.rst
> +* ``delete_all_previous`` - all previously upladed daily usages for
Done.

2016-09-26 10:32 UTC, xor-xor commented on doc/api.rst
> +              ("service": "<service name>" | "service_id": <service ID> | "service_uid": "<service UID>"),
Done.

2016-09-26 10:40 UTC, xor-xor commented on doc/api.rst
> +generated in Scrooge's Admin.
Done.

2016-09-26 12:01 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +def get_usages_for_save(pricing_service_usage):
Done.

2016-09-26 12:02 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +def save_usages(pricing_service_usage):
yes

2016-09-26 12:03 UTC, mkurek commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +class TastyPieLikeTokenAuthentication(TokenAuthentication):
ok

2016-09-26 12:03 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +def save_usages(pricing_service_usage):
Done.

2016-09-27 07:19 UTC, mkurek approved these changes

2016-09-27 07:21 UTC, merged