WIP Add upload file with usages
allegro/ralph_pricing pull request #510
Opened 2016-09-21 12:20 UTC by szok

2016-09-27 05:36 UTC, mkurek requested changes

2016-09-27 05:36 UTC, mkurek commented on src/ralph_scrooge/media/scrooge/app/allocationclient/controller.js
> +        .success(function(data) {
move it to the line above

2016-09-27 05:36 UTC, mkurek commented on src/ralph_scrooge/media/scrooge/app/allocationclient/controller.js
> +        .error(function(){
ditto

2016-09-27 05:36 UTC, mkurek commented on src/ralph_scrooge/media/scrooge/partials/taballocationclientdivision.html
> -      <th>Charged service</th>
why?

2016-09-27 05:36 UTC, mkurek commented on src/ralph_scrooge/utils/csv_utils.py
> +import csv
unify this with https://github.com/allegro/ralph_pricing/blob/develop/src/ralph_scrooge/csvutil.py

2016-09-27 05:36 UTC, mkurek commented on src/ralph_scrooge/rest/allocationclient.py
> +                if row.get('service_uid'):
please add option for passing service_env_id too (for some backward-compatibility)

2016-10-03 06:30 UTC, szok commented on src/ralph_scrooge/media/scrooge/partials/taballocationclientdivision.html
> -      <th>Charged service</th>
My mistake :(

2016-10-05 14:16 UTC, xor-xor commented on src/ralph_scrooge/rest/allocationadmin.py
> +                                ' and environment id {1}'.format(
What about `Service environment does not exist for service with ID {0} and environment with ID {1}`..?

2016-10-05 14:22 UTC, xor-xor commented on src/ralph_scrooge/rest/allocationadmin.py
> +def get_allocationadmin_from_file(file):
What about adding a note somewhere re: how structure of this file should look like..? I mean, I know it's CSV, but what to you expect in its columns?

2016-10-05 14:23 UTC, xor-xor commented on src/ralph_scrooge/rest/allocationclient.py
> +def get_allocation_from_file(file):
Same remark as in `get_allocationadmin_from_file` (i.e. description of records).

2016-10-10 07:00 UTC, mkurek requested changes

2016-10-10 07:00 UTC, mkurek commented on src/ralph_scrooge/rest/allocationadmin.py
> +        if row.get('service_env_id'):
we should first check (validate) if all required keys (cost, forecast_cost (it shouldn't be required imo - we could assume 0 here as a default), service_env_id or service_uid or service_name + environment) are set. We could also check headers of csv;

2016-10-10 07:00 UTC, mkurek commented on src/ralph_scrooge/rest/allocationadmin.py
> +        if len(row.get('id', '')) > 1:
why do we need this?

2016-10-10 07:00 UTC, mkurek commented on src/ralph_scrooge/rest/allocationclient.py
> +            'value': row['value']
this differs from `get_allocationadmin_from_file` only by `value` (cost/forecast_cost in `get_allocationadmin_from_file`) - could we unify this?

2016-10-10 07:00 UTC, mkurek commented on src/ralph_scrooge/rest/allocationclient.py
> +            post_data = request.DATA
shouldn't we `json.loads` this? what's the difference between `request.raw_post_data` and `request.DATA`?

2016-10-10 08:31 UTC, szok commented on src/ralph_scrooge/rest/allocationadmin.py
> +        if len(row.get('id', '')) > 1:
Yes, because I don't add to result if 'id' is not exist.

2016-10-11 07:52 UTC, mkurek requested changes

2016-10-11 07:52 UTC, mkurek commented on src/ralph_scrooge/csvutil.py
> +    return (result, headers)
invert it - return headers first

2016-10-11 07:57 UTC, szok commented on src/ralph_scrooge/csvutil.py
> +    return (result, headers)
donedone

2016-10-11 07:59 UTC, mkurek approved these changes

2016-10-11 08:04 UTC, merged