[WiP] Add endpoint for uploading team time divisions.
allegro/ralph_pricing pull request #516
Opened 2016-09-29 10:14 UTC by xor-xor

Do not merge! Preview only!

2016-10-05 07:07 UTC, mkurek requested changes

2016-10-05 07:07 UTC, mkurek commented on doc/api.rst
> +Here, we can see that our team (given in URL by its ID, i.e. ``156``)
change it to `123` to be the same as in the example

2016-10-05 07:07 UTC, mkurek commented on doc/api.rst
> +   a person who is associated with a team, and is an owner of at least
are you sure about "and is an owner of at least one service"? I'm not :)

2016-10-05 07:07 UTC, mkurek commented on src/ralph_scrooge/rest/team_time_division.py
> +    def validate_service_uid(self, attrs, source):
imo we don't have to validate service_uid and env name separately - ServiceEnvioronment validation (like in `validate` method) will be enough (and we'll have 3x less db queries).

2016-10-05 07:07 UTC, mkurek commented on src/ralph_scrooge/rest/team_time_division.py
> +        team_cost__team__id=team,
`team_cost__team=team` (join for matching by id is not necessary)

2016-10-05 07:07 UTC, mkurek commented on src/ralph_scrooge/rest/team_time_division.py
> +            percent_total += d['percent']
what if someone does not provide percent key or it's not a number? at which point is it validated? could we get there if there is some data corrupted earlier?

2016-10-05 07:07 UTC, mkurek commented on src/ralph_scrooge/rest/team_time_division.py
> +            "{}/{}".format(
couldn't you use tuple here - `(d['service_uid'], d['environment'])`?

2016-10-05 07:07 UTC, mkurek commented on src/ralph_scrooge/rest/team_time_division.py
> +    authentication_classes = (TastyPieLikeTokenAuthentication,)
couldn't we force regular DRF authentication here?

2016-10-05 07:07 UTC, mkurek commented on src/ralph_scrooge/rest/team_time_division.py
> +                {'error': err}, status=status.HTTP_400_BAD_REQUEST
shouldn't we return 404 here?

2016-10-05 07:07 UTC, mkurek commented on src/ralph_scrooge/rest/team_time_division.py
> +        tsep, created = TeamServiceEnvironmentPercent.objects.get_or_create(
do we need to use `get_or_create` here? since we're deleting all previous values before, and validating uniqueness of the data (service-env), imo we could just simply create new records.

2016-10-05 12:06 UTC, xor-xor commented on doc/api.rst
> +Here, we can see that our team (given in URL by its ID, i.e. ``156``)
Done.

2016-10-05 12:15 UTC, xor-xor commented on doc/api.rst
> +   a person who is associated with a team, and is an owner of at least
Right. I've changed this sentence to: "A team manager in Scrooge's is a person who is associated with a given team, and is marked as an owner of some (zero or more) services [...]", although "being an owner of zero services" sounds kind of strange to me ;) Maybe we should completely drop that part re: ownership..?

2016-10-05 12:18 UTC, xor-xor commented on src/ralph_scrooge/rest/team_time_division.py
> +    authentication_classes = (TastyPieLikeTokenAuthentication,)
...and lost the ability to authenticate users with old API keys (i.e., the ones from TastyPie)..?

2016-10-05 12:23 UTC, xor-xor commented on src/ralph_scrooge/rest/team_time_division.py
> +        tsep, created = TeamServiceEnvironmentPercent.objects.get_or_create(
Right. I was influenced by [this piece of code](https://github.com/xor-xor/ralph_pricing/blob/b275031b762e440db1d715258b880d0ab597e334/src/ralph_scrooge/rest/allocationclient.py#L325).

2016-10-05 12:36 UTC, xor-xor commented on src/ralph_scrooge/rest/team_time_division.py
> +        tsep, created = TeamServiceEnvironmentPercent.objects.get_or_create(
Done.

2016-10-05 12:50 UTC, xor-xor commented on src/ralph_scrooge/rest/team_time_division.py
> +                {'error': err}, status=status.HTTP_400_BAD_REQUEST
Done

2016-10-05 12:53 UTC, xor-xor commented on src/ralph_scrooge/rest/team_time_division.py
> +            "{}/{}".format(
We could, but I'd stay with strings, because we re-use them when the error message is being constructed.

2016-10-05 13:05 UTC, xor-xor commented on src/ralph_scrooge/rest/team_time_division.py
> +    def validate_service_uid(self, attrs, source):
Done.

2016-10-05 13:11 UTC, xor-xor commented on src/ralph_scrooge/rest/team_time_division.py
> +        team_cost__team__id=team,
Done.

2016-10-05 13:25 UTC, xor-xor commented on src/ralph_scrooge/rest/team_time_division.py
> +            percent_total += d['percent']
ad. 1. You'll get "This field is required."
ad. 2. You'll get "value must be a float."
ad. 3. [Here](url)..? :wink: 
ad. 4. Could you expand "some data corrupted earlier"..?

2016-10-11 10:28 UTC, mkurek commented on doc/api.rst
> +   a person who is associated with a team, and is an owner of at least
Maybe "A team manager in Scrooge's is a person who is associated with a given team and is allowed to allocate team resources (time) to services"?

2016-10-11 10:39 UTC, xor-xor commented on doc/api.rst
> +   a person who is associated with a team, and is an owner of at least
Done.

2016-10-11 13:40 UTC, mkurek approved these changes

2016-10-12 07:43 UTC, szok approved these changes

2016-10-12 07:47 UTC, merged