[WIP] Upgrade django version from 1.4 to 1.5
allegro/ralph_pricing pull request #525
Opened 2016-10-04 14:29 UTC by szok

Upgrade django version from 1.4 to 1.5 and migration user profile to user model

2016-10-07 10:54 UTC, xor-xor commented
Code-wise seems to be OK, but to finally approve this PR, I need to check if Scrooge works properly after those changes - I'll let you know :wink:

2016-10-07 13:55 UTC, xor-xor approved these changes

2016-10-12 06:08 UTC, mkurek requested changes

2016-10-12 06:08 UTC, mkurek commented on src/ralph_scrooge/admin.py
> +class ScroogeUserAdmin(UserAdmin):
couldn't we use default django admin for user here?

2016-10-12 06:08 UTC, mkurek commented on src/ralph_scrooge/models/owner.py
> +class ScroogeUser(AbstractUser):
imo we don't need nick, birth_date, gender, city, activation_token, department, manager, location, segment, company fields in scrooge. Actually, we could remove all of these fields :)

2016-10-12 06:08 UTC, mkurek commented on src/ralph_scrooge/models/owner.py
> +        db_table = 'scrooge_user'
do we need this?

2016-10-12 06:15 UTC, szok commented on src/ralph_scrooge/admin.py
> +class ScroogeUserAdmin(UserAdmin):
I use this to add additional fields. If we don't need it I will remove this class

2016-10-12 06:16 UTC, szok commented on src/ralph_scrooge/models/owner.py
> +class ScroogeUser(AbstractUser):
ok

2016-10-12 06:16 UTC, szok commented on src/ralph_scrooge/models/owner.py
> +        db_table = 'scrooge_user'
Yes, without this did not work

2016-10-25 10:37 UTC, mkurek requested changes

2016-10-25 10:37 UTC, mkurek commented on src/ralph_scrooge/migrations/0030_copy_userprofile_to_scrooge_user.py
> +class Migration(SchemaMigration):
shouldn't it be DataMigration? http://south.readthedocs.io/en/latest/tutorial/part3.html#data-migrations

2016-10-25 10:37 UTC, mkurek commented on src/ralph_scrooge/migrations/0030_copy_userprofile_to_scrooge_user.py
> +            Owner = orm['ralph_scrooge.Owner']
couldn't we get rid of `Owner` model here? we could use `ScroogeUser` directly instead.

2016-10-25 10:37 UTC, mkurek commented on src/ralph_scrooge/models/owner.py
>  class Owner(TimeTrackable):
as I said earlier, everything pointing to Owner (ForeignKey to Owner) could be changed to ForeignKey to ScroogeUser

2016-10-25 10:37 UTC, mkurek commented on src/ralph_scrooge/admin.py
> +                'employee_id', 'profit_center', 'cost_center', 'department',
you've removed these fields from model - remove them here too (or even use plain django model admin for user)

2016-10-26 09:30 UTC, mkurek approved these changes

2016-10-26 09:30 UTC, merged