Add endpoint for fetching usage values/costs per day/month.
allegro/ralph_pricing pull request #530
Opened 2016-10-14 12:53 UTC by xor-xor

Docs will be added once we will have this new `v0.10` hierarchy finally discussed. By that time, this endpoint should be considered as private and subject to changes.

Please note that in `v0.10` we are dropping support for auth tokens in TastyPie format - from now on, only tokens in DjRF's format will be accepted (`v0.9` supports both of them - i.e. the same token can be provided in two ways).

2016-10-24 13:37 UTC, mkurek approved these changes

2016-10-24 13:37 UTC, mkurek commented on doc/api.rst
> +    * leave "Show usage type in report" checked. (XXX such field doesn't exist?)
afair it's `active` right now

2016-10-24 13:37 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    group_by = serializers.CharField(default='day')
doesn't DRF have ChoiceField? http://www.tomchristie.com/rest-framework-2-docs/api-guide/fields#choicefield

2016-10-24 13:37 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +            attrs[source] = UsageType.objects.all()
here you return all `UsageType`s, but later you check for `BaseUsage` - what case is valid?

2016-10-24 13:37 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +def date_range(start, stop, step=timedelta(days=1)):
you could use `dateutil.rrange` as well

2016-10-24 13:37 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    for usage_type in usage_types:
please annotate by path - then you'll have to do just one PR - and you could post-process it in python (it should be faster than querying multiple times this table - afaik path field doesn't have index as well). 

The "flow" here could be as follows:
* filter daily costs by service-env and date range
* group queryset by date (month?) and path
* do a postprocessing in python - create some data structure for storing costs by date, and nested one, where you'll store costs by following parts of `path` (splitted by `/`)

The result should be exactly the same, but you'll make much less DB queries (1 instead of N)

You could also consider calculating total cost in python (you have to iterate over each "row" of result either way, so summing total cost up shouldn't be a problem here, but calling to DB might be) :)

2016-10-24 13:37 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +def fetch_costs(service_env, usage_types, date_from, date_to, group_by):
`usage_types` might be misleading here - it is (or should be) list of `BaseUsage` instances, not `UsageType`

2016-10-24 13:38 UTC, mkurek requested changes
@xor-xor what do you think about this groupping?

2016-10-25 09:48 UTC, xor-xor commented on doc/api.rst
> +    * leave "Show usage type in report" checked. (XXX such field doesn't exist?)
Done.

2016-10-25 10:05 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    group_by = serializers.CharField(default='day')
Done. Alghouth it leads me to define choices as:
```
GROUP_BY_CHOICES = (
    ('day', 'day'),
    ('month', 'month'),
)
```
...which IMO looks kind of weird - but on the other hand, we get validation of this field for free, which is a good thing.

2016-10-25 10:14 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +            attrs[source] = UsageType.objects.all()
Both of them..? :wink: 

I mean, this later check for `BaseUsage`s if for the case when someone would provide a `PricingService` in `usage_type` field.

So maybe I should return all `BaseUsage`s here (instead of `UsageType`s)..? But to be honest - this relation between `BaseUsage` and `UsageType` and `PricingService` is quite confusing to me (i.e. that they are all kind of equal in this context - especially `PricingService` being a subclass of `BaseUsage`) :wink:

2016-10-25 10:16 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +def fetch_costs(service_env, usage_types, date_from, date_to, group_by):
Yes, it really is misleading/confusing (see one of my previous comments).

2016-10-25 10:42 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +def date_range(start, stop, step=timedelta(days=1)):
You mean `dateutil.rrule`..? I'm not sure if it's really needed here - for instance, it returns `datetime.datetime` objects, while this module uses `datetime.date` exclusively, so we would have to convert its results. And "my" `date_range` is only 3 lines long, so... :wink:

2016-10-25 10:42 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +def date_range(start, stop, step=timedelta(days=1)):
sure - it could stay as it is

2016-10-25 11:03 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    for usage_type in usage_types:
Regarding the first part of your comment - I'll try to provide an alternative version of `fetch_costs` function, so we'd be able to compare them performance-wise.

And speaking of the second part - but what about the fact that total cost is not the sum of costs calculated for selected usage types..? IMO we have to make a separate DB query here anyway.

2016-10-25 12:51 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +            attrs[source] = UsageType.objects.all()
Done.

2016-11-02 07:42 UTC, mkurek requested changes

2016-11-02 07:42 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +        if len(errors) > 0:
maybe just `if errors`? :)

2016-11-02 07:42 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    # Django, see: http://stackoverflow.com/q/37446551/5768173.
we have Django 1.10 now :)

2016-11-02 07:42 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +        # This workaround can be removed once we switch to DjRF 3.x and get rid
we have drf 3.x now - you could remove it :)

2016-11-02 07:42 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    ).extra({group_by: truncate_date})
`extra` is deprecated now (https://docs.djangoproject.com/en/1.10/ref/models/querysets/#django.db.models.query.QuerySet.extra) - we could use `TruncMonth` here IMO (https://docs.djangoproject.com/en/1.10/ref/models/database-functions/#django.db.models.functions.datetime.TruncMonth or http://stackoverflow.com/a/8746532/761782)

2016-11-02 07:42 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +            date_to.replace(day=1) + delta,
maybe `date_range` should iterate to `date_to` including it (`<=` instead of `<`)? Then we wouldn't have to add this `+delta` here and when we group by day (to increase it by one)?

2016-11-02 07:42 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    aggregated_costs = initial_qs.values_list(
wouldn't it be better to use `values` here instead of `values_list`? Then we'd get rid of this "magic" indexes like `ac[5]` and use field names like `ac['path']`

2016-11-02 07:42 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    initial_qs = DailyCost.objects_tree.filter(
we should filter here `depth` to be max 2

2016-11-02 07:42 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    if their types are not in `types`.
please describe here why we can't do this at database level

2016-11-02 07:42 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +                '_type_symbol': ac[2],
add some comment here why couldn't we use type symbol directly as a key in `d` dict

2016-11-02 07:56 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    ).extra({group_by: truncate_date})
I know, this is exactly what I'm going to do (I'm in the middle of a transition to Django 1.10 / DjRF 3.x) :wink:

2016-11-02 07:57 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +        # This workaround can be removed once we switch to DjRF 3.x and get rid
I know - I'm in the middle of a transition to Django 1.10 / DjRF 3.x.

2016-11-02 07:58 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    initial_qs = DailyCost.objects_tree.filter(
Hmm... As far as I remember, we both decided that the maximum level of nesting in DailyCosts will be 1, so where that new value comes from..?

2016-11-02 07:59 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    # Django, see: http://stackoverflow.com/q/37446551/5768173.
I know :wink: As I stated in my previous comments - I'm in the middle of a transition to this version.

2016-11-02 09:32 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +        if len(errors) > 0:
Done.

2016-11-02 09:34 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    # Django, see: http://stackoverflow.com/q/37446551/5768173.
Done.

2016-11-02 09:36 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    ).extra({group_by: truncate_date})
Done.

2016-11-02 09:42 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    initial_qs = DailyCost.objects_tree.filter(
It is possible that there will be costs with greater depth. By default it's turned off (using `SAVE_ONLY_FIRST_DEPTH_COSTS` in settings), but when you turn in on (setting it to `False`), for each `PricingService` with `universal` "calculating model" (not only the ones with fixes prices) whole subtree of costs will be saved (for example, PricingService 1 is dependent on PricingService2 which has costs from some base UsageTypes, Extra Costs and Teams - theoretically it could be nested infinitely). 

Cutting of here at `depth__lte=1` (or `depth__in=(0,1)` - I don't know which will be faster for DB) will work in cases when someone has this variable (`SAVE_ONLY_FIRST_DEPTH_COSTS` set to `False`).

2016-11-02 09:49 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +        # This workaround can be removed once we switch to DjRF 3.x and get rid
Done.

2016-11-02 10:08 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    initial_qs = DailyCost.objects_tree.filter(
Done (I went with `depth__lte=1`, as it seems to be more idiomatic than the latter form).

2016-11-02 10:17 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +            date_to.replace(day=1) + delta,
I'm over the fence with this idea :wink: On the one hand - you're right - it would simplify the code a little bit - but on the other - it would introduce some inconsistency / unexpected behaviour related to how "normal" `range` behaves in Python. Personally, I would be rather surprised to see that any iterator having `_range` in its name would include the last value of the interval given as argument.

2016-11-02 10:22 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +                '_type_symbol': ac[2],
You mean why it starts with `_`..? That's because it's just a temporary key, that is removed later in the process, so anyone dealing with this code shouldn't rely on it. But yes, you're right with adding a comment.

2016-11-02 10:24 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +                '_type_symbol': ac[2],
Done.

2016-11-02 10:28 UTC, mkurek commented on src/ralph_scrooge/rest/service_environment_costs.py
> +            date_to.replace(day=1) + delta,
good point with python range. So leave it as it is :)

2016-11-02 10:58 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    if their types are not in `types`.
Done (I've added a comment related to this, but in a different, more suitable location).

2016-11-02 11:38 UTC, xor-xor commented on src/ralph_scrooge/rest/service_environment_costs.py
> +    aggregated_costs = initial_qs.values_list(
Good point (done).

2016-11-03 22:29 UTC, mkurek approved these changes

2016-11-04 08:04 UTC, szok approved these changes

2016-11-04 08:07 UTC, merged