Add mgmt command for (re)calculation of daily costs per single day.
allegro/ralph_pricing pull request #532
Opened 2016-10-25 09:25 UTC by xor-xor

2016-10-25 09:54 UTC, mkurek requested changes

2016-10-25 09:54 UTC, mkurek commented on src/ralph_scrooge/management/commands/scrooge_calculate_dailycosts.py
> +        ).values_list('date', flat=True).exists()
no need for `values_list` to check if any record `exists`

2016-10-25 09:54 UTC, mkurek commented on src/ralph_scrooge/management/commands/scrooge_calculate_dailycosts.py
> +        processed_costs = collector.process(date_, forecast, plugins=plugins)
we could think about wrapping these 3 calls to collector into some Collector's method, which will have date (start and end?), forecast and plugins param and will do the rest - @xor-xor what do you think?

2016-10-25 11:57 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_calculate_dailycosts.py
> +        ).values_list('date', flat=True).exists()
Ah, right - I'm a copy & paste victim :wink:

2016-10-25 12:08 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_calculate_dailycosts.py
> +        processed_costs = collector.process(date_, forecast, plugins=plugins)
Makes sense, but only if this method will be used anywhere else apart from this mgmt command - do you see any use for it in the future..?

On the other hand, I see that `Collector` already has methods like `process_period` and`process`, so adding another one, with similar name/behavior can be confusing to ppl working with it later.

2016-10-27 14:37 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_calculate_dailycosts.py
> +        processed_costs = collector.process(date_, forecast, plugins=plugins)
Done.

2016-11-02 13:19 UTC, mkurek approved these changes

2016-11-02 13:30 UTC, szok commented on src/ralph_scrooge/management/commands/scrooge_calculate_dailycosts.py
> +        pricing_service_names_verified = [ps.name for ps in pricing_services]
Why not
pricing_services.vlaues_list('name', flat=True)
?

2016-11-03 09:32 UTC, szok approved these changes

2016-11-03 09:34 UTC, merged