[WiP] Notifications about anomalies in usages
allegro/ralph_pricing pull request #544
Opened 2016-11-08 10:07 UTC by xor-xor

For preview only - do not merge yet!

2016-11-09 21:18 UTC, mkurek requested changes

2016-11-09 21:18 UTC, mkurek commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +# -*- coding: utf-8 -*-
don't name this command like `scrooge_XXX` - this prefix was useful when scrooge was tied to ralph. Now, when scrooge is standalone, this prefix is not necessary anymore.

2016-11-09 21:18 UTC, mkurek commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +from collections import OrderedDict
collections (unlike dateutil) is in stdlib - change order of imports

2016-11-09 21:18 UTC, mkurek commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +# XXX This could be overridden on per-UsageType basis (e.g. in some dict loaded
👍

2016-11-09 21:18 UTC, mkurek commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +def get_negative_month_range(end_date=None):
why negative?

2016-11-09 21:18 UTC, mkurek commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +            results[usage][date_] = _get_usage_value(
fetch all usages at once. Sth like:

```
daily_usages = dict(DailyUsage.objects.filter(date__gte=start_date, date__lte=end_date, type=usage).values_list('date').annotate(Sum('value'))
for date_ in get_negative_month_range():
   results[usage][date_] = daily_usages.get(date_, 0)
```

2016-11-09 21:18 UTC, mkurek commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +def _get_usage_values_for_date_range(usage_types):
shouldn't this method take `end_date` as a param?

2016-11-09 21:18 UTC, mkurek commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +    missing_values = OrderedDict()
does it have to be ordered dict? maybe you could use defaultdict?

2016-11-09 21:18 UTC, mkurek commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +            dest='usage_names',  # XXX what about using symbols here..?
👍 for symbols

2016-11-09 21:18 UTC, mkurek commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +    """XXX This is just a temporary function for debugging/development."""
i'll keep it (maybe improve it a little bit) to get some output during dry-run

2016-11-09 21:18 UTC, mkurek commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +    ret = OrderedDict()
defaultdict?

2016-11-09 21:18 UTC, mkurek commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +            'big_changes': big_changes,
we should figure out some better name for this :)

2016-11-09 21:18 UTC, mkurek commented on src/ralph_scrooge/models/usage.py
> +    upload_freq = db.PositiveIntegerField(
this param should be (somehow) considered in anomalies detection. in my opinion we should take some margin (ex. 2 days - it could be general for all frequencies or different for each) and expect uploads for day/week/month after end of the period (end of day, end of week, and of month + some margin) for this period of time. Example (considering margin as 2 days):
* for daily frequency: on 8.11 we should expect uploads for 6.11 and before
* for weekly frequency: on 8.11 (end of 31.10 - 6.10 week + 2 days) we should expect uploads for week 31.10 - 6.11 (but, on 9.11, 10.11, ..., 14.11 we should expect usages upload for max. 6.11, not later)
* for monthly frequency: on 2.11 (end of october + 2 days margin) we should expect uploads for whole october (but on 3.11, ..., 1.12 we should expect uploads for max. 31.10, not later)

2016-11-10 10:30 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +# -*- coding: utf-8 -*-
Done.

2016-11-10 10:31 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +from collections import OrderedDict
Done.

2016-11-10 10:35 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +# XXX This could be overridden on per-UsageType basis (e.g. in some dict loaded
Actually, I have a better idea - instead of putting this into settings, I'd add the `change_tolerance` (or `diff_tolerance`) field to `UsageType`, with default value `0.2` - that will allow to customize it by owners of given usage type via admin panel (and I guess that this default value won't be OK for everybody, so...).

What do you think about this..?

2016-11-10 10:40 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +def get_negative_month_range(end_date=None):
Because we get iterator over range, where `end_date` is yesterday (by default), and `start_date` is yesterday - 1 month.
But if you have some better idea for the name here, I'm open for suggestions :wink:

2016-11-10 10:41 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +            'big_changes': big_changes,
Yes, sure - it's just a temporary one. Let me know if you have some ideas for this.

2016-11-10 10:57 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +            dest='usage_names',  # XXX what about using symbols here..?
Done.

2016-11-10 11:43 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +    missing_values = OrderedDict()
I needed OrderedDict for development purposes only, so now almost all occurences of it are replaced with normal dicts (except for the place where I prepare the list of dates for e-mail template - I need them to be sorted there).

2016-11-10 11:44 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +    ret = OrderedDict()
"Normal" one is just enough here.

2016-11-10 12:17 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +    """XXX This is just a temporary function for debugging/development."""
Done.

2016-11-10 12:22 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +def _get_usage_values_for_date_range(usage_types):
Yup (done).

2016-11-10 13:18 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +            'big_changes': big_changes,
What about `unusual_changes` or `spikes`..?

2016-11-10 13:18 UTC, xor-xor commented on src/ralph_scrooge/management/commands/scrooge_detect_usage_anomalies.py
> +            results[usage][date_] = _get_usage_value(
Right (done).

2016-11-17 12:08 UTC, xor-xor commented on src/ralph_scrooge/models/usage.py
> +    upload_freq = db.PositiveIntegerField(
Done.

2016-11-17 15:28 UTC, mkurek requested changes

2016-11-17 15:28 UTC, mkurek commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +log = logging.getLogger(__name__)
we use `logger` everywhere for such things- could you change it to keep it compatible with the rest of the code?

2016-11-17 15:28 UTC, mkurek commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +            max_date = date - freq_margin + relativedelta(day=1, days=-1)
could you describe it briefly? as far as i understand this is going to return last day of previous month?

2016-11-17 15:28 UTC, mkurek commented on src/ralph_scrooge/migrations/0003_auto_20161117_1248.py
> +        ('ralph_scrooge', '0002_auto_20161104_1323'),
probably https://github.com/allegro/ralph_pricing/pull/551 will be merged faster, so remember to bump migration number and dependent number

2016-11-17 15:28 UTC, mkurek commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +def _get_max_expected_date(usage, date):
could you write some unit tests for this method?

2016-11-17 15:28 UTC, mkurek commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +def get_negative_month_range(end_date):
Is it possible to make this method more generic - it could take number of months or days (to subtract) as a param?

2016-11-17 15:28 UTC, mkurek commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +            max_date = date - freq_margin + relativedelta(day=1, days=-1)
And there is a "bug" IMO - when "monthly" freq is used, couple of first days of the month will never be verified. For example:
assuming today is 2016.11.02, we're assuming, that usages for October might not be uploaded - so `max_date` is 2016.09.30 (so no day will be verified, because `min_date` (`start_date`) is `2016.11.02 - month == 2016.10.02`). Assuming today is 2016.11.03, usages for October should be uploaded, so `max_date` is 2016.10.31 - but, again, start date is `2016.11.03 - month == 2016.10.03` - what about 2016.10.01 and 2016.10.02? They will be not verified at all.

Possible solution for that might be to set start_date for some more than month ago (ex. 40 days) - but the perfect here would be to parametrize it somewhere.

2016-11-17 15:28 UTC, mkurek commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +    anomalies_to_report = _group_anomalies_by_owner(anomalies)
could we move grouping by owner out of this function? `_detect_anomalies` will probably be reused in GUI someday, but we'll have to present anomalies by type only. Grouping by owner is necessary only for mailing.

2016-11-17 15:28 UTC, mkurek commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +                ret[owner] = {'missing_values': {}, 'unusual_changes': {}}
consider defaultdicts here

2016-11-17 15:28 UTC, mkurek commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +    ret = {}
consider defaultdicts here

2016-11-17 15:28 UTC, mkurek commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +            '',  # TODO(xor-xor): Do we need plain-text version of the message?
no

2016-11-17 15:28 UTC, mkurek commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +        print("-" * 79)
![](https://cdn.meme.am/instances/65219958.jpg)

2016-11-18 09:46 UTC, xor-xor commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +log = logging.getLogger(__name__)
Done.

2016-11-18 09:49 UTC, xor-xor commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +            '',  # TODO(xor-xor): Do we need plain-text version of the message?
:+1:

2016-11-18 09:50 UTC, xor-xor commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +        print("-" * 79)
Done.

2016-11-18 09:50 UTC, xor-xor commented on src/ralph_scrooge/migrations/0003_auto_20161117_1248.py
> +        ('ralph_scrooge', '0002_auto_20161104_1323'),
OK.

2016-11-18 10:22 UTC, xor-xor commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +    anomalies_to_report = _group_anomalies_by_owner(anomalies)
Done.

2016-11-18 10:52 UTC, xor-xor commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +    ret = {}
Done.

2016-11-18 10:56 UTC, xor-xor commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +                ret[owner] = {'missing_values': {}, 'unusual_changes': {}}
Done.

2016-11-18 11:06 UTC, xor-xor commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +def get_negative_month_range(end_date):
Done.

2016-11-18 13:00 UTC, xor-xor commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +def _get_max_expected_date(usage, date):
Done.

2016-11-18 13:34 UTC, xor-xor commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +            max_date = date - freq_margin + relativedelta(day=1, days=-1)
Done & done.
Actually, the solution for the "bug" above was quite simple - I've added a param `align_to_month` to `get_negative_month_range`, which is set to `True` when `UsageType.upload_freq` is set to `'monthly'` - it extends the returned range to the beginning of month.

2016-11-23 10:39 UTC, szok approved these changes

2016-11-23 10:39 UTC, szok commented on src/ralph_scrooge/models/usage.py
> +        default=1,
Better use:
default=UsageTypeUploadFreq. daily.id

2016-11-23 10:39 UTC, szok commented on src/ralph_scrooge/templatetags/joinby.py
> +def joinby(values, sep):
👍

2016-11-23 14:50 UTC, xor-xor commented on src/ralph_scrooge/models/usage.py
> +        default=1,
Done.

2016-11-24 14:18 UTC, mkurek approved these changes

2016-11-24 14:19 UTC, merged