Add IPInfo model and migrate data from PricingObject to IPInfo
allegro/ralph_pricing pull request #551
Opened 2016-11-17 14:11 UTC by szok

2016-11-17 14:52 UTC, mkurek requested changes

2016-11-17 14:52 UTC, mkurek commented on src/ralph_scrooge/migrations/0004_copy_ipinfo.py
> +            DailyPricingObject.objects.filter(pricing_object=po).update(
use here DailyUsage rather than DailyPricingObject. Create daily pricing object for today (`dpo = default_pricing_object.get_daily_pricing_object(today)`) and run sth like `DailyUsage.objects.filter(daily_pricing_object__pricing_object=po).update(daily_pricing_object=dpo)`

2016-11-18 09:53 UTC, mkurek requested changes

2016-11-18 09:53 UTC, mkurek commented on src/ralph_scrooge/migrations/0004_copy_ipinfo.py
> +    for d in duplicates:
add some log/print here what ip is currently processed

2016-11-24 13:22 UTC, mkurek approved these changes

2016-11-24 13:31 UTC, xor-xor commented on src/ralph_scrooge/models/pricing_object.py
> +        self.number = int(ipaddress.ip_address(self.name or 0))
Can we safely assume, that we will never get a `ValueError` from `ip_address` here..? Or putting it in other way: does `self.name` guarantee to always hold a valid IPv4/IPv6 address..?

2016-11-24 14:19 UTC, mkurek commented
@szok bump migrations numbers

2016-11-25 08:12 UTC, xor-xor commented on src/ralph_scrooge/models/pricing_object.py
> +            raise ValidationError(_('Is not a valid ip address'))
s/ip/IP/ :wink:

2016-11-25 08:12 UTC, xor-xor approved these changes

2016-11-25 09:07 UTC, merged