Add filtering by service on `pricingserviceusage` endpoint in API.
allegro/ralph_pricing pull request #558
Opened 2016-11-24 11:59 UTC by quamilek

In some reason user would like to filter stored usages coming from
one of service, not fetching usages from all services. This pull
request implement filtering `pricingserviceusages` endpoint by
`service_id` parameter in GET method.

2016-11-24 12:38 UTC, mkurek approved these changes

2016-11-24 13:18 UTC, xor-xor requested changes

2016-11-24 13:18 UTC, xor-xor commented on src/ralph_scrooge/tests/rest/test_pricing_service_usages.py
> +        # check filtering by `service_id`
I'd rather create a separate test for this, instead of adding it to another, which is quite lengthy by itself anyway.

2016-11-24 13:18 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +def get_usages(usages_date, pricing_service, service=None):
What about renaming `service` to `filter_by_service` here..?

2016-11-24 13:18 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +def get_usages(usages_date, pricing_service, service=None):
Please update docstring for this function.

2016-11-24 13:18 UTC, xor-xor commented on src/ralph_scrooge/rest/pricing_service_usages.py
> +            err_msg = (
No need to split this into 4 lines, 1 should be enough.

2016-11-25 11:38 UTC, xor-xor approved these changes

2016-11-25 11:40 UTC, merged