Provide ability to acknowledge detected usage anomalies.
allegro/ralph_pricing pull request #597
Opened 2017-03-07 09:40 UTC by xor-xor

It also adds a management command `delete_old_usage_anomaly_acks` which should be added to crontab (by default, it deletes acks older than 2 months, but this number can be changed via `-m` option).

2017-03-09 11:55 UTC, mkurek requested changes

2017-03-09 11:55 UTC, mkurek commented on src/ralph_scrooge/management/commands/delete_old_usage_anomaly_acks.py
> +        if qs.exists():
why not `if qs_count`? you don't need then extra query then (I know, I know - uber optimisation in the most important piece of scrooge 👍 )

2017-03-09 11:55 UTC, mkurek commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +    unusual_changes_ = {}
consider sth like:
```
unusual_changes_ = {}
for ut in unusual_changes.keys():
    ut_changes = unusual_changes[ut]
    acks = set(UsageAnomalyAck.objects.filter(
        type=ut, anomaly_date__in=[change[0] for change in ut_changes]
    ).values_list('anomaly_date', flat=True))
    unusual_changes_[ut] = [change for change in changes if change[0] not in acks]
return unusual_changes_
```

Wouldn't it be easier (and faster)?

2017-03-09 11:55 UTC, mkurek commented on src/ralph_scrooge/urls.py
> +        name='services_costs_report',  # XXX why this URL is called like that?
check if it is used somewhere and you could rename it

2017-03-09 11:55 UTC, mkurek commented on src/ralph_scrooge/views/anomalies_ack.py
> +        ut_id = request.GET.get('ut_id')
can we put these params into url, to call it like `http://scrooge/ack/<ut_id>/<date>`, ex. `http://scrooge/ack/10/2017-03-09`?

2017-03-13 10:14 UTC, xor-xor commented on src/ralph_scrooge/management/commands/delete_old_usage_anomaly_acks.py
> +        if qs.exists():
Yep, right. Fixed.

2017-03-13 10:21 UTC, xor-xor commented on src/ralph_scrooge/management/commands/detect_usage_anomalies.py
> +    unusual_changes_ = {}
Yes, probably ;) (fixed)

2017-03-13 10:30 UTC, xor-xor commented on src/ralph_scrooge/views/anomalies_ack.py
> +        ut_id = request.GET.get('ut_id')
I did that at first, but then I started to think - "what's the point of structuring this URL like that, since this endpoint is private and shouldn't be 'discoverable'..?" - and I think that this question remains valid ;)

2017-03-13 11:12 UTC, xor-xor commented on src/ralph_scrooge/urls.py
> +        name='services_costs_report',  # XXX why this URL is called like that?
Done.

2017-03-13 12:09 UTC, mkurek commented on src/ralph_scrooge/views/anomalies_ack.py
> +        ut_id = request.GET.get('ut_id')
Being private doesn't mean that we don't have to design this url properly :) IMO it has nothing to do with discoverability - rather validation and easiness.

2017-03-13 12:38 UTC, xor-xor commented on src/ralph_scrooge/views/anomalies_ack.py
> +        ut_id = request.GET.get('ut_id')
But we fully control the shape of the links in notifications emails and users are not expected to enter them manually (actually, they shouldn't do that at all), so what's the point..? I.e. validation of what and easiness for who..? ;)

2017-03-13 14:36 UTC, xor-xor commented on src/ralph_scrooge/views/anomalies_ack.py
> +        ut_id = request.GET.get('ut_id')
OK, I've changed it.

2017-03-13 17:17 UTC, mkurek approved these changes

2017-03-14 07:38 UTC, merged