[WiP] Add validation of data for recalculation of monthly costs report.
allegro/ralph_pricing pull request #599
Opened 2017-03-24 13:03 UTC by xor-xor

2017-03-28 06:36 UTC, mkurek requested changes

2017-03-28 06:36 UTC, mkurek commented on src/ralph_scrooge/plugins/validations.py
> +        for ut in self.active_usage_types:
it's not so simple IMO. We should exclude here `UsageType`s with `usage_type == Service Usage Type` attached to `PricingService` with plugin type `fixed price`.

We could approach this from different side: take here all `PricingService`s with `fixed_price` plugin type and check if every `UsageType` attached to them has price defined.

2017-03-28 06:36 UTC, mkurek commented on src/ralph_scrooge/plugins/validations.py
> +        # XXX(mkurek): only active or maybe active *and* linked to some
👍 we should take here only:

`UsageType`s with `BU` type
or 
`UsageType`s with `SU` type AND assigned to some `PricingService`

2017-03-28 06:36 UTC, mkurek commented on src/ralph_scrooge/plugins/validations.py
> +        """There should be no usage type where percents do not sum up to 100%.
usage type -> pricing service?

2017-03-28 08:26 UTC, xor-xor commented on src/ralph_scrooge/plugins/validations.py
> +        # XXX(mkurek): only active or maybe active *and* linked to some
You mean something like this:
```
for ut in self.active_usage_types.filter(usage_type__in=['BU', 'SU']):
    if ut.usage_type == 'SU':
        if not ServiceUsageTypes.objects.filter(
            usage_type=ut,
            start__lte=self.date,
            end__gte=self.date,
        ).exists():
            continue
    if not DailyUsage.objects.filter(date=self.date, type=ut).exists():
        self.errors.append(
            'no usage(s) uploaded for usage type "{}"'.format(ut.name)
        )
```
?

2017-03-28 08:29 UTC, xor-xor commented on src/ralph_scrooge/plugins/validations.py
> +        """There should be no usage type where percents do not sum up to 100%.
Changed to:   "There should be no pricing service with usage type(s) that together do not sum up to 100%.".

2017-03-28 09:02 UTC, mkurek commented on src/ralph_scrooge/plugins/validations.py
> +        # XXX(mkurek): only active or maybe active *and* linked to some
looks good

2017-04-07 10:15 UTC, mkurek requested changes

2017-04-07 10:15 UTC, mkurek commented on src/ralph_scrooge/plugins/cost/collector.py
> +        from_gui=False,
could you name it more general, ex. `perform_validation`?

2017-04-07 10:15 UTC, mkurek commented on src/ralph_scrooge/plugins/validations.py
> +        setattr(self, 'errors', errors)
do you have to use `setattr` here? wouldn't `self.errors = errors` work?

2017-04-07 10:15 UTC, mkurek commented on src/ralph_scrooge/plugins/validations.py
> +        Exception.__init__(self, message)
why not `super`?

2017-04-07 10:15 UTC, mkurek commented on src/ralph_scrooge/plugins/validations.py
> +    # XXX(mkurek): And also, what about checking (dynamic) extra costs..?
👍 - there should be two checks for dynamic extra costs:
1) if cost is defined
2) if usage type (using which cost is allocated) has some daily usages for particular day

So it should be combination of validator for extra cost and usage type

2017-04-07 10:15 UTC, mkurek commented on src/ralph_scrooge/plugins/validations.py
> +                sum_price = UsagePrice.objects.filter(**q).aggregate(
you could combine this into single query (end of [this](https://docs.djangoproject.com/en/1.10/topics/db/aggregation/#generating-aggregates-over-a-queryset) paragraph ):
```
cost_field = 'cost' if not self.forecast else 'forecast_cost'
price_field = 'price' if not self.forecast else 'forecast_price'
up = UsagePrice.objects.filter(**q).aggregate(sum_cost=Sum(cost_field), sum_price=Sum(price_field))
sum_cost, sum_price = up['sum_cost'], up['sum_price']
```

2017-04-07 10:15 UTC, mkurek commented on src/ralph_scrooge/plugins/validations.py
> +            q = 'forecast_cost'
q -> cost_field

2017-04-07 10:15 UTC, mkurek commented on src/ralph_scrooge/rest_api/private/monthly_costs.py
> +    def run(cls, day, forecast, from_gui=False):
imo we don't need this param here

2017-04-07 10:15 UTC, mkurek commented on src/ralph_scrooge/rest_api/private/monthly_costs.py
> +            result = collector.process(day, forecast, from_gui=from_gui)
imo `from_gui` could be always `True` here

2017-04-07 10:15 UTC, mkurek commented on src/ralph_scrooge/tests/plugins/test_validations.py
> +    # XXX(mkurek): Do we need/want to test all above with `forecast=True`
probably not - but if you like to you could use subclass and set `self.forecast = True/False` in subclasses - then use `self.forecast` in proper tests :)

2017-04-07 10:15 UTC, mkurek commented on src/ralph_scrooge/rest_api/private/monthly_costs.py
> +        # XXX(mkurek): What does True/False in data mean?
data is True/False and means, that job ended successfully or not

2017-04-10 12:25 UTC, xor-xor commented on src/ralph_scrooge/plugins/cost/collector.py
> +        from_gui=False,
Done.

2017-04-10 12:26 UTC, xor-xor commented on src/ralph_scrooge/plugins/validations.py
> +        setattr(self, 'errors', errors)
What's the difference, effectively..? ;) (but OK, I'll change that)

2017-04-10 12:29 UTC, xor-xor commented on src/ralph_scrooge/plugins/validations.py
> +        Exception.__init__(self, message)
Done.

2017-04-10 12:55 UTC, xor-xor commented on src/ralph_scrooge/plugins/validations.py
> +                sum_price = UsagePrice.objects.filter(**q).aggregate(
Right, thx for suggestion.

2017-04-10 12:58 UTC, xor-xor commented on src/ralph_scrooge/plugins/validations.py
> +            q = 'forecast_cost'
Done.

2017-04-10 13:20 UTC, mkurek commented on src/ralph_scrooge/plugins/validations.py
> +        setattr(self, 'errors', errors)
just cleanliness of the code :)

2017-04-10 14:31 UTC, xor-xor commented on src/ralph_scrooge/rest_api/private/monthly_costs.py
> +        # XXX(mkurek): What does True/False in data mean?
OK, thx.

2017-04-10 14:36 UTC, xor-xor commented on src/ralph_scrooge/rest_api/private/monthly_costs.py
> +            result = collector.process(day, forecast, from_gui=from_gui)
Yeah, right - I didn't know that this method is used only by GUI.

2017-04-10 14:39 UTC, xor-xor commented on src/ralph_scrooge/rest_api/private/monthly_costs.py
> +    def run(cls, day, forecast, from_gui=False):
Removed.

2017-04-11 08:42 UTC, xor-xor commented on src/ralph_scrooge/tests/plugins/test_validations.py
> +    # XXX(mkurek): Do we need/want to test all above with `forecast=True`
Good idea (done).

2017-04-11 13:17 UTC, xor-xor commented on src/ralph_scrooge/plugins/validations.py
> +    # XXX(mkurek): And also, what about checking (dynamic) extra costs..?
Done.

2017-04-13 08:30 UTC, mkurek commented on src/ralph_scrooge/plugins/cost/collector.py
> +        if perform_validation:
could you add some switch to settings for it too (to easily turn it off in case of any undesired behaviour, especially on first recalculation). It could be set to `True` by default.

2017-04-13 09:56 UTC, xor-xor commented on src/ralph_scrooge/plugins/cost/collector.py
> +        if perform_validation:
Good idea (done).

2017-04-13 09:57 UTC, mkurek approved these changes

2017-04-13 10:13 UTC, merged