Recalculate daily costs after each usages upload.
allegro/ralph_pricing pull request #600
Opened 2017-04-03 14:34 UTC by xor-xor

2017-04-04 06:06 UTC, mkurek requested changes

2017-04-04 06:06 UTC, mkurek commented on src/ralph_scrooge/rest_api/public/v0_9/pricing_service_usages.py
> +    # TODO(xor-xor): Consider recalculation of forecast costs as well.
👍

2017-04-04 06:06 UTC, mkurek commented on src/ralph_scrooge/rest_api/public/v0_9/pricing_service_usages.py
> +    _recalculate_costs(pricing_service_usage['date'])
this should be executed only if usages are saved for PricingService with fixed prices - otherwise we could get "ddosed" by pushing to API changes for other Pricing Services, especially the ones with `overwrite=False`.

2017-04-04 12:53 UTC, xor-xor commented on src/ralph_scrooge/rest_api/public/v0_9/pricing_service_usages.py
> +    # TODO(xor-xor): Consider recalculation of forecast costs as well.
Done.

2017-04-04 12:53 UTC, xor-xor commented on src/ralph_scrooge/rest_api/public/v0_9/pricing_service_usages.py
> +    _recalculate_costs(pricing_service_usage['date'])
Done.

2017-04-07 10:34 UTC, mkurek approved these changes

2017-04-07 14:42 UTC, merged