Add management command for costs report pre-validation
allegro/ralph_pricing pull request #610
Opened 2017-04-25 12:07 UTC by mkurek

2017-04-25 12:40 UTC, xor-xor requested changes

2017-04-25 12:40 UTC, xor-xor commented on src/ralph_scrooge/management/commands/_utils.py
> +def valid_date(date_):
It is in utils already: https://github.com/allegro/ralph_pricing/blob/develop/src/ralph_scrooge/utils/common.py#L130 ;) What about importing it as `valid_date` to your mgmt command..?

2017-04-25 13:24 UTC, mkurek commented on src/ralph_scrooge/management/commands/_utils.py
> +def valid_date(date_):
True, I'll fix it :)

2017-04-25 13:52 UTC, mkurek commented on src/ralph_scrooge/management/commands/_utils.py
> +def valid_date(date_):
done

2017-04-26 13:40 UTC, xor-xor requested changes

2017-04-26 13:40 UTC, xor-xor commented on src/ralph_scrooge/management/commands/costs_report_prevalidation.py
> +from ralph_scrooge.utils.common import validate_date
s/validate_date/validate_date as valid_date/

2017-04-26 13:40 UTC, xor-xor commented on src/ralph_scrooge/management/commands/costs_report_prevalidation.py
> +            type=validate_date,
s/validate_date/valid_date/

2017-04-26 13:40 UTC, xor-xor commented on src/ralph_scrooge/management/commands/detect_cycles.py
> +            type=validate_date,
s/validate_date/valid_date/

2017-04-26 13:40 UTC, xor-xor commented on src/ralph_scrooge/management/commands/detect_cycles.py
> +from ralph_scrooge.utils.common import validate_date
s/validate_date/validate_date as valid_date/

2017-04-28 06:36 UTC, mkurek commented
@xor-xor fixed all comments

2017-04-28 07:09 UTC, xor-xor approved these changes

2017-04-28 07:09 UTC, merged