Feature/real time service update
allegro/ralph_pricing pull request #623
Opened 2017-12-18 08:13 UTC by MarekBleschke

2017-12-19 13:43 UTC, mkurek requested changes

2017-12-19 13:43 UTC, mkurek commented on src/ralph_scrooge/plugins/subscribers/service_environment.py
> +        u'Start service environment processing for service with name: '
import from future instead of using `u''`:
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
```

2017-12-19 13:43 UTC, mkurek commented on src/ralph_scrooge/plugins/subscribers/service_environment.py
> +    service.profit_center = default_profit_center
don't set `default_profit_center` here - service might have already set `profit_center`.

2017-12-19 13:43 UTC, mkurek commented on src/ralph_scrooge/plugins/subscribers/service_environment.py
> +    service, created = Service.objects.get_or_create(ci_uid=event_data['uid'])
why not `update_or_create`?

2017-12-19 13:43 UTC, mkurek commented on src/ralph_scrooge/plugins/subscribers/service_environment.py
> +    # Delete obsolete environments.
do not delete environment if it is obsolete - it should be still assigned to service for historical reasons

2017-12-21 12:23 UTC, mkurek approved these changes

2018-01-10 07:42 UTC, ar4s approved these changes

2018-01-11 08:08 UTC, merged