identify environment by name instead of ralph_id
allegro/ralph_pricing pull request #625
Opened 2018-02-01 12:26 UTC by MarekBleschke

2018-02-01 12:37 UTC, mkurek commented on src/ralph_scrooge/models/service.py
> -    ralph3_id = db.IntegerField(
why are you removing this field (and, for example, leaving ci_id)?

2018-02-01 13:18 UTC, MarekBleschke commented on src/ralph_scrooge/models/service.py
> -    ralph3_id = db.IntegerField(
I want to move from identifying by ralph_id to identifying environments by name. Change with integration with hermes introduced a problem because we don't have ralph_id in incoming data so it's not added to new env entry. Environment update from ralph3_service_environment.py added duplicated environment entry (as it's looking existing env by ralph_id) which caused problems.

If you prefer I can leave this field, but I thought it could be confusing.

2018-02-01 13:22 UTC, mkurek commented on src/ralph_scrooge/models/service.py
> -    ralph3_id = db.IntegerField(
it's good idea to identify env by name, but I'd remove `ci_id` and `ci_uid` fields too

2018-02-01 13:27 UTC, MarekBleschke commented on src/ralph_scrooge/models/service.py
> -    ralph3_id = db.IntegerField(
ok

2018-02-02 07:40 UTC, MarekBleschke commented on src/ralph_scrooge/models/service.py
> -    ralph3_id = db.IntegerField(
done

2018-02-02 11:29 UTC, ar4s requested changes

2018-02-02 11:29 UTC, ar4s commented on src/ralph_scrooge/admin.py
>  class EnvironmentAdmin(UpdateReadonlyMixin, admin.ModelAdmin):
``UpdateReadonlyMixin`` is not necessary now

2018-02-02 13:12 UTC, MarekBleschke commented on src/ralph_scrooge/admin.py
>  class EnvironmentAdmin(UpdateReadonlyMixin, admin.ModelAdmin):
removed

2018-02-02 13:25 UTC, mkurek approved these changes

2018-02-02 13:26 UTC, ar4s approved these changes

2018-02-05 07:58 UTC, merged