Report skip empty rows
allegro/ralph_pricing pull request #641
Opened 2018-07-26 12:21 UTC by mkurek

2018-07-27 07:03 UTC, MarekBleschke submitted a review, later dismissed

2018-07-27 10:48 UTC, ar4s approved these changes

2018-07-30 06:01 UTC, ar4s approved these changes

2018-07-30 06:04 UTC, ar4s requested changes

2018-07-30 06:04 UTC, ar4s commented on src/ralph_scrooge/settings/base.py
> +        '': {
#639 contains this change

2018-07-30 07:39 UTC, mkurek commented on src/ralph_scrooge/settings/base.py
> +        '': {
fixed

2018-07-30 08:24 UTC, ar4s approved these changes

2018-07-30 08:59 UTC, MarekBleschke approved these changes

2018-07-30 09:28 UTC, merged