Support sync of accepted costs between Scrooge instances
allegro/ralph_pricing pull request #650
Opened 2018-09-28 12:38 UTC by mkurek

2018-10-04 09:14 UTC, MarekBleschke commented on src/ralph_scrooge/sync/publisher.py
> +        response = requests.post(  # todo: retry, timeout
This todo is for later?

2018-10-04 09:14 UTC, MarekBleschke commented on src/ralph_scrooge/settings/base.py
> +ACCEPTED_COSTS_SYNC_RECIPIENTS = []
I think it would be good to add comment about how ACCEPTED_COSTS_SYNC_RECIPIENTS data format should look like.

2018-12-04 12:03 UTC, szymi- approved these changes

2018-12-04 12:08 UTC, szymi- requested changes
Approved by misclick.

2021-06-02 11:45 UTC, closed without merging